fullnameOverride: hasher
image:
  repository: dockercoins/hasher
  tag: "v0.1"
service:
  type: ClusterIP
  port: 80
livenessProbe:
  httpGet: null
  tcpSocket:
    port: http
readinessProbe:
  httpGet: null
  tcpSocket:
    port: http
